spring:
  application:
    name: ums

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/umsdb}
    username: ${DB_USERNAME:ums_user}
    password: ${DB_PASSWORD:ums_pass}
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 5000
      initialization-fail-timeout: 60000

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false

server:
  port: ${SERVER_PORT:8080}
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.ums: DEBUG
