spring:
  jpa:
    properties:
      hibernate:
        format_sql: true
    show-sql: true

  flyway:
    clean-disabled: false  # allow flyway:clean in dev only

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.orm.jdbc.bind: TRACE
    com.ums: DEBUG

management:
  tracing:
    sampling:
      probability: 1.0
